# Generated by Django 4.0.6 on 2022-07-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_app', '0003_alter_course_options_alter_course_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField(default=True)),
                ('phone_number', models.CharField(max_length=8)),
                ('email', models.EmailField(default=True, max_length=254)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.course')),
            ],
            options={
                'ordering': ['-first_name'],
                'unique_together': {('first_name', 'last_name', 'phone_number', 'email')},
            },
        ),
    ]
