# Generated by Django 4.0.6 on 2022-07-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_alter_course_options_alter_course_unique_together'),
        ('students_app', '0003_rename_owner_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='courses_app.course'),
        ),
    ]
